services:
-   name: keycloak-auth
    host: keycloak
    port: 8080
    routes:
    -   name: realm-route
        paths:
        - /auth
        strip_path: false
        protocols:
        - https
        https_redirect_status_code: 308
-   name: dev_api
    host: host.docker.internal
    port: 8000
    routes:
    -   name: dev-api-main-route
        paths:
        - /dev_api/
        strip_path: false
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        protocols:
        - https
        https_redirect_status_code: 308
plugins:
-   name: cors
    config:
        origins:
        - localhost
        methods:
        - GET
        - POST
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        exposed_headers:
        - X-Auth-Token
        credentials: true
        max_age: 3600
        preflight_continue: false
-   name: rate-limiting
    config:
        second: 1000
        minute: 1000
        hour: 1000
        policy: local
        fault_tolerant: true
        hide_client_headers: false
        redis_ssl: false
        redis_ssl_verify: false
-   name: ip-restriction
    config:
        allow:
        - 127.0.0.0/24
        - 172.18.0.0/24
        - 192.168.0.0/16
-   name: oidc
    service: dev_api
    config:
        client_id: dev-api-client
        client_secret: fUVSFAyZwXrkaDQDQINt81IIz3ZDgVqC
        unauth_action: auth
        discovery: https://devapi.my/auth/realms/dev_api/.well-known/openid-configuration
        scope: openid
        logout_path: /dev_api/api/v1/logout
        redirect_after_logout_uri: https://devapi.my/auth/realms/dev_api/protocol/openid-connect/logout
        post_logout_redirect_uri: https://devapi.my/dev_api/api/v1/public/bye
        redirect_after_logout_with_id_token_hint: 'yes'
        ignore_auth_filters: (.*)public(.*)$
_format_version: '3.0'
