version: "3.6"

networks:
  app_global:
    driver: bridge

services:
  keycloak_db:
    extends:
      file: src/components/auth/db/docker-compose.yml
      service: db
    container_name: keycloak_db
    networks:
      - app_global

  keycloak:
    extends:
      file: src/components/auth/keycloak/docker-compose.yml
      service: keycloak_web

    container_name: keycloak_web
    depends_on:
      - keycloak_db
    networks:
      - app_global

  postgress_admin:
    extends:
      file: src/components/auth/db/docker-compose.yml
      service: adminer
    container_name: keycloak_db_admin
    depends_on:
      - keycloak_db
    networks:
      - app_global

  kong_gateway:
    extends:
      file: src/components/gateway/kong/docker-compose.yml
      service: kong
    container_name: kong_gateway
    depends_on: 
      - keycloak
    networks:
      - app_global

  dev_api:
    extends:
      file: apps/dev_api/docker-compose.yaml
      service: api
    container_name: dev_api
    networks:
      - app_global
    profiles: 
      - default
      - "!dev"
      - vm
      - staging

