version: "3.3"

services:
  kong:
    image: local/docker-kong-oidc:3.4.0-2
    volumes:
      - "./config:/usr/local/kong/declarative"
      - "./logs:/usr/logs"
    environment:
      # https://docs.konghq.com/gateway/3.7.x/reference/configuration
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      # - KONG_PROXY_ACCESS_LOG=/usr/logs/proxy_access.log
      # - KONG_ADMIN_ACCESS_LOG=/usr/logs/admin_acess.log
      # - KONG_PROXY_ERROR_LOG=/usr/logs/proxy_err.txt
      # - KONG_ADMIN_ERROR_LOG=/usr/logs/admin_err.txt
      - KONG_PROXY_LISTEN=0.0.0.0:8082, 0.0.0.0:8443 ssl
      - KONG_ADMIN_LISTEN=0.0.0.0:8083, 0.0.0.0:8444 ssl
      - KONG_LOG_LEVEL=debug
      - KONG_PLUGINS=bundled,oidc
    ports:
      - "8082:8082/tcp"
      - "8083:8083/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
