version: "3.3"

services:
  kong:
    build:
      context: .
    image: ${EXT_KONG_IMAGE_NAME}
    volumes:
      - "${EXT_KONG_CERT_DIRECTORY}:/usr/local/kong/certs"
      - ./logs:/usr/local/kong/logs
    environment:
      # https://docs.konghq.com/gateway/3.7.x/reference/configuration
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      # - KONG_PROXY_ACCESS_LOG=/usr/logs/proxy_access.log
      # - KONG_ADMIN_ACCESS_LOG=/usr/logs/admin_acess.log
      # - KONG_PROXY_ERROR_LOG=/usr/logs/proxy_err.txt
      # - KONG_ADMIN_ERROR_LOG=/usr/logs/admin_err.txt
      - KONG_PROXY_LISTEN=${EXT_KONG_HTTP_HOST}:${EXT_KONG_HTTP_PORT_INTERNAL}, ${EXT_KONG_HTTP_HOST}:${EXT_KONG_SSL_PORT_INTERNAL} ssl
      - KONG_ADMIN_LISTEN=${EXT_KONG_HTTP_HOST}:${EXT_KONG_ADMIN_HTTP_PORT_INTERNAL}, ${EXT_KONG_HTTP_HOST}:${EXT_KONG_ADMIN_SSL_PORT_INTERNAL} ssl
      - KONG_LOG_LEVEL=debug
      - KONG_PLUGINS=bundled,oidc
      - KONG_SSL_CERT=/usr/local/kong/certs/${EXT_KONG_CERT_NAME}
      - KONG_SSL_CERT_KEY=/usr/local/kong/certs/${EXT_KONG_CERT_KEY_NAME}

      # Substituted into kong.yml at container startup
      - CARVANTAGE_KONG_KC_CLIENT_ID=${CARVANTAGE_KONG_KC_CLIENT_ID}
      - CARVANTAGE_KONG_KC_CLIENT_SECRET=${CARVANTAGE_KONG_KC_CLIENT_SECRET}
      - CARVANTAGE_KONG_KC_DISCOVERY_URL=${CARVANTAGE_KONG_KC_DISCOVERY_URL}
      - CARVANTAGE_KONG_LOGOUT_PATH=${CARVANTAGE_KONG_LOGOUT_PATH}
      - CARVANTAGE_KONG_REDIRECT_AFTER_LOGOUT=${CARVANTAGE_KONG_REDIRECT_AFTER_LOGOUT}
      - CARVANTAGE_KONG_POST_LOGOUT_REDIRECT=${CARVANTAGE_KONG_POST_LOGOUT_REDIRECT}
    ports:
      - "${EXT_KONG_HTTP_PORT_EXTERNAL}:${EXT_KONG_HTTP_PORT_INTERNAL}/tcp"
      - "${EXT_KONG_ADMIN_HTTP_PORT_EXTERNAL}:${EXT_KONG_ADMIN_HTTP_PORT_INTERNAL}/tcp"
      - "${EXT_KONG_SSL_PORT_EXTERNAL}:${EXT_KONG_SSL_PORT_INTERNAL}/tcp"
      - "${EXT_KONG_ADMIN_SSL_PORT_EXTERNAL}:${EXT_KONG_ADMIN_SSL_PORT_INTERNAL}/tcp"

    # Uncomment to run in verbose mode
    # command:
    #   - "kong"
    #   - "start"
    #   - "--v"