version: "3.6"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASS}
    volumes:
      - ${KEYCLOAK_DB_DATA_DIR}:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - ${PG_ADMINER_PORT}:8080
